[33mcommit 0d43fffff11b54925944d25411f87326af743ec6[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mjazzy-dev[m[33m, [m[1;31morigin/jazzy-dev[m[33m)[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 21 18:22:53 2025 +0300

    Code refactored and robot for Gazebo simulation prepared.

[33mcommit b6c968dc2c4b89c602e257de7a86552249f246d7[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Sat Apr 19 21:56:26 2025 +0300

    Fixed bugs, world files modified so they can be executed local

[33mcommit 0ecac5d723d1c3aec433817b77f8cd0d1a018a01[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Fri Apr 18 01:08:43 2025 +0300

    Gazebo plugins added and xacro files adapted.

[33mcommit 5fde6c203942000863f011dc321651aa6468df95[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Wed Apr 16 23:32:08 2025 +0300

    Code refactored.

[33mcommit 9faf603ac58a31dde830c3933e817f6723e05387[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Wed Apr 16 20:54:43 2025 +0300

    Code refactored.

[33mcommit 45f02354932b80a33f1ce1c77bf23a938cf88006[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 14 21:14:26 2025 +0300

    Gazebo launch file modified to provide default values.

[33mcommit 73fd84b67b422c52a87ee7edff929d75e528c904[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 14 19:42:27 2025 +0300

    Package for simulation in gazebo added.

[33mcommit b1970f382dfaea5b7c2a0b15ce96b1a4657dd06c[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 14 15:10:33 2025 +0300

    pepper.urdf.xacro modified (wheel orientation and position)

[33mcommit 0b6eff895bc10c3252c7050fb12e28f832317116[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 14 02:15:29 2025 +0300

    mimic joints reactivated, because of the physics engine change from DART to Bullet ~ (ros2_control still not implemented).

[33mcommit f198a3a385d5704bf850f2f38333658dc9620dbb[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Mon Apr 14 01:00:03 2025 +0300

    Spawning error in Gazebo fixed (ros2_control still not implemented).

[33mcommit 840984e581110c6a0f51a83fff156ade574eb1df[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Sun Apr 13 23:59:56 2025 +0300

    Error in pepper.urdf.xacro file fixed, to spawn robot in Gazebo.

[33mcommit e18ed3fa4fee39b37c17f43e434e5f05b6e7453c[m[33m ([m[1;32mmaster[m[33m)[m
Author: michailtam <mi.tamvak@gmail.com>
Date:   Thu Apr 10 23:47:21 2025 +0300

    Initial commit
