controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    upper_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    lower_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# Settings for each controller
diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    left_wheel_names: ["WheelFL"]
    right_wheel_names: ["WheelFR"]
    wheel_separation: 0.31
    wheel_radius: 0.08
    use_stamped_vel: true
    joints: [WheelFL, WheelFR]
    command_interfaces: [velocity]
    state_interfaces: [position, velocity]
    open_loop: false

head_controller:
  ros__parameters:
    joints: [HeadYaw, HeadPitch]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.02
    open_loop: false
    
upper_body_controller:
  ros__parameters:
    joints: [LShoulderPitch, LShoulderRoll, RShoulderPitch, RShoulderRoll,
             LElbowYaw, LElbowRoll, RElbowYaw, RElbowRoll,
             LWristYaw, RWristYaw]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.02
    state_publish_rate: 50.0       # Hz
    action_monitor_rate: 20.0      # Hz
    open_loop: false

lower_body_controller:
  ros__parameters:
    joints: [HipRoll, HipPitch, KneePitch]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.75
      stopped_velocity_tolerance: 0.02
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    open_loop: false