controller_manager:
  ros__parameters:
    update_rate: 100  # update_rate specifies how often (in Hz) the controllers should be updated.
    use_sim_time: true

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    body_part_controller:
      type: joint_trajectory_controller/JointTrajectoryController

 
# Define the parameters for each controller
diff_controller:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ["WheelFL"]
    right_wheel_names: ["WheelFR"]

    wheel_seperation: 0.31
    wheel_radius: 0.08

    use_stamped_vel: true

    joints:
      - WheelFL
      - WheelFR

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

body_part_controller:
  ros__parameters:
    joints:
      # Head
      - HeadYaw
      - HeadPitch
      - HipRoll
      - HipPitch
      - KneePitch

      # Left shoulder
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw

      # Left shoulder
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw

      # Left arm
      - LHand
      - LFinger42
      - LFinger33
      - LFinger21
      - LFinger13
      - LFinger32
      - LFinger11
      - LFinger22
      - LFinger41
      - LFinger12
      - LFinger23
      - LFinger43
      - LFinger31
      - LThumb1
      - LThumb2
      
      # Right arm
      - RHand
      - RFinger41
      - RFinger12
      - RFinger31
      - RFinger32
      - RFinger22
      - RFinger13
      - RFinger21
      - RFinger23
      - RFinger11
      - RFinger43
      - RFinger42
      - RFinger33
      - RThumb1
      - RThumb2
  

    # The controller will expect position commands as input for each of these joints.
    command_interfaces:
      - position
 
    # Receive position data as the state feedback from the hardware interface.
    state_interfaces:
      - position
      - velocity
 
    # If true, the controller will not use any feedback from the system
    # (e.g., joint positions, velocities, efforts) to compute the control commands.
    open_loop_control: false
 
    # When set to true, it allows the controller to integrate the trajectory goals it receives.
    # This means that if the goal trajectory only specifies positions, the controller will
    # numerically integrate the positions to compute the velocities and accelerations required
    # to follow the trajectory.
    allow_integration_in_goal_trajectories: true
 
    # Allow non-zero velocity at the end of the trajectory
    allow_nonzero_velocity_at_trajectory_end: true