controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    upper_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    lower_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# Settings for each controller
# parameter description: https://control.ros.org/jazzy/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html
diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    
    left_wheel_names: ["WheelFL"]
    right_wheel_names: ["WheelFR"]
    
    wheel_separation: 0.31
    wheel_radius: 0.08

    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_limited_velocity: true # Makes the controller to publish limited velocity commands
    publish_wheel_data: true

    use_stamped_vel: true
    enable_odom_tf: true

    # linear:
    #   x:
    #     has_velocity_limits    : true
    #     max_velocity           : 1.0  # m/s
    #     min_velocity           : -0.5 # m/s
    #     has_acceleration_limits: true
    #     max_acceleration       : 0.8  # m/s^2
    #     min_acceleration       : -0.4 # m/s^2
    #     has_jerk_limits        : false
    #     max_jerk               : 5.0  # m/s^3
    # angular:
    #   z:
    #     has_velocity_limits    : true
    #     max_velocity           : 1.7  # rad/s
    #     has_acceleration_limits: true
    #     max_acceleration       : 1.5  # rad/s^2
    #     has_jerk_limits        : false
    #     max_jerk               : 2.5  # rad/s^3
    
head_controller:
  ros__parameters:
    joints: [HeadYaw, HeadPitch]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.02
    action_monitor_rate: 20.0      # Hz
    open_loop: false

upper_body_controller:
  ros__parameters:
    joints: [LShoulderPitch, LShoulderRoll, RShoulderPitch, RShoulderRoll,
             LElbowYaw, LElbowRoll, RElbowYaw, RElbowRoll,
             LWristYaw, RWristYaw]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.02
    action_monitor_rate: 20.0      # Hz
    open_loop: false
    
lower_body_controller:
  ros__parameters:
    joints: [HipRoll, HipPitch, KneePitch]
    command_interfaces: [position]
    state_interfaces: [position]
    constraints:
      goal_time: 0.75
      stopped_velocity_tolerance: 0.02
    action_monitor_rate: 20.0
    open_loop: false
    